### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by jcohenadad** [jcohenadad/model-seg-ms-mp2rage-monai#1]
~~~
33/85, train_loss: 0.6002
34/85, train_loss: 0.5994
35/85, train_loss: 0.5996
36/85, train_loss: 0.5987
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model-seg-ms-mp2rage-monai/venv-mp2rage/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 367, in reduce_storage
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 198, in DupFd
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model-seg-ms-mp2rage-monai/venv-mp2rage/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 367, in reduce_storage
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 198, in DupFd
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
37/85, train_loss: 0.5997
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 145, in _serve
    send(conn, destination_pid)
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 50, in send
    reduction.send_handle(conn, new_fd, pid)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 183, in send_handle
    with socket.fromfd(conn.fileno(), socket.AF_UNIX, socket.SOCK_STREAM) as s:
  File "/usr/lib/python3.10/socket.py", line 545, in fromfd
    nfd = dup(fd)
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model-seg-ms-mp2rage-monai/train.py", line 204, in <module>
    for batch_data in train_loader:
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model-seg-ms-mp2rage-monai/venv-mp2rage/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model-seg-ms-mp2rage-monai/venv-mp2rage/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model-seg-ms-mp2rage-monai/venv-mp2rage/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model-seg-ms-mp2rage-monai/venv-mp2rage/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model-seg-ms-mp2rage-monai/venv-mp2rage/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 159, in recvfds
    raise EOFError
EOFError
~~~

**Comment by jcohenadad** [comment]
Not a space issue:
~~~
/dev/nvme0n1p1                       733G  203G  523G  28% /mnt/nvme
~~~

**Comment by jcohenadad** [comment]
Possibly related:
- https://stackoverflow.com/questions/45665991/multiprocessing-returns-too-many-open-files-but-using-with-as-fixes-it-wh
- https://github.com/dfm/emcee/issues/350
- https://github.com/pytorch/pytorch/issues/11201
