### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by jcohenadad** [jcohenadad/model-seg-ms-mp2rage-monai#2]
Run: https://wandb.ai/jcohenadad/MP2RAGE_MS_lesion_3D_Segmentation/runs/kea2c12z/files/output.log

```console
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model-seg-ms-mp2rage-monai/train_wandb.py", line 328, in <module>
    for batch_data in train_loader:
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 159, in recvfds
    raise EOFError
EOFError
35/85, train_loss: 0.3251
```

Possibly a different cause than https://github.com/jcohenadad/model-seg-ms-mp2rage-monai/issues/1

**Comment by jcohenadad** [comment]
Re-ran to see if it fails at the same location.

**Comment by jcohenadad** [comment]
Another run, issue happened approximately at the same time (epoch 11): https://wandb.ai/jcohenadad/MP2RAGE_MS_lesion_3D_Segmentation/runs/bd53rxvs/logs?workspace=user-jcohenadad

**Comment by jcohenadad** [comment]
Possibly related to https://discuss.pytorch.org/t/pytorch-windows-eoferror-ran-out-of-input-when-num-workers-0/25918?page=2

Will try reduce num_worker to 1 instead of 2.

Also failing 👎  And much faster (epoch 2):

````console
55/85, train_loss: 0.5036
56/85, train_loss: 0.5028
57/85, train_loss: 0.5035
58/85, train_loss: 0.4971
59/85, train_loss: 0.5004
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 367, in reduce_storage
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 198, in DupFd
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
60/85, train_loss: 0.4982
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 145, in _serve
    send(conn, destination_pid)
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 50, in send
    reduction.send_handle(conn, new_fd, pid)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 183, in send_handle
    with socket.fromfd(conn.fileno(), socket.AF_UNIX, socket.SOCK_STREAM) as s:
  File "/usr/lib/python3.10/socket.py", line 545, in fromfd
    nfd = dup(fd)
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model-seg-ms-mp2rage-monai/train_wandb.py", line 324, in <module>
    for batch_data in train_loader:
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 159, in recvfds
    raise EOFError
EOFError
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb:
wandb: Run history:
wandb:    learning_rate ▁
wandb:       train/loss █▇▆▆▆▅▅▅▄▄▄▄▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁
wandb: train/loss_epoch ▁
wandb:
wandb: Run summary:
wandb:    learning_rate 0.001
wandb:       train/loss 0.49823
wandb: train/loss_epoch 0.57637
wandb:
wandb: 🚀 View run solar-armadillo-5 at: https://wandb.ai/jcohenadad/MP2RAGE_MS_lesion_3D_Segmentation/runs/lpfqwr8w
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230311_101051-lpfqwr8w/logs
````

> **Warning**
> The output [log showed by wandb](https://wandb.ai/jcohenadad/MP2RAGE_MS_lesion_3D_Segmentation/runs/lpfqwr8w/files/output.log) does not include all the information showed on the STDOUT of the Terminal (copied above). Notably, the "too many open files" does not appear.

**Comment by jcohenadad** [comment]
Does not seem to be caused by GPU's RAM saturation:

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/2482071/224492270-810c039e-8507-4616-9e7e-5ba6cc9517ef.png">

**Comment by jcohenadad** [comment]
Added this line (as per #1):
```python
torch.multiprocessing.set_sharing_strategy('file_system')
```
